import React, { useState, useEffect } from 'react';
import { ShieldCheck, RefreshCw, Clock } from 'lucide-react';
import type { ApprovalRequest } from '../types';

export const ApprovalsPanel: React.FC = () => {
  const [approvals] = useState<ApprovalRequest[]>([]);
  const [isLoading, setIsLoading] = useState(false);

  const fetchApprovals = async () => {
    setIsLoading(true);
    try {
      const res = await fetch('/approvals');
      if (res.ok) {
        // Will populate when items exist
      }
    } catch (e) {
      console.error('Fetch approvals error', e);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchApprovals();
  }, []);

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      <div className="bg-white border border-slate-200/80 rounded-2xl p-7 shadow-soft-md">
        <div className="flex items-center justify-between mb-5">
          <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-slate-500">
            <ShieldCheck className="w-4 h-4 text-brand-600" />
            <span>Human-in-the-Loop Compliance Gate</span>
          </div>
          <button
            onClick={fetchApprovals}
            disabled={isLoading}
            className="flex items-center gap-2 px-4 py-2 bg-slate-100 hover:bg-slate-200 text-slate-700 font-semibold rounded-xl text-xs transition-all shadow-soft-sm"
          >
            <RefreshCw className={`w-3.5 h-3.5 ${isLoading ? 'animate-spin' : ''}`} />
            <span>Refresh Queue</span>
          </button>
        </div>

        <p className="text-sm text-slate-600 leading-relaxed mb-6">
          Action requests generated by downstream agents carrying binding or external effects require explicit human compliance officer authorization before execution by the Tool-Exec Agent.
        </p>

        {approvals.length === 0 ? (
          <div className="p-10 text-center border-2 border-dashed border-slate-200 rounded-2xl bg-slate-50/50">
            <Clock className="w-10 h-10 text-slate-400 mx-auto mb-3" />
            <div className="text-sm font-bold text-slate-800 mb-1">Approval Queue Active & Empty</div>
            <div className="text-xs text-slate-500 max-w-sm mx-auto leading-relaxed">
              When a query results in a proposed action (e.g. export filing, submit redline), it will be queued here for manual verification.
            </div>
          </div>
        ) : (
          <div className="space-y-4">
            {approvals.map(req => (
              <div key={req.approval_id} className="p-5 bg-slate-50 border border-slate-200 rounded-xl">
                <div className="text-sm font-bold text-slate-900">{req.tool_name}</div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
};
