import React, { useState, useEffect } from 'react';
import { ShieldCheck, RefreshCw, Clock, CheckCircle2, XCircle, Terminal, AlertTriangle } from 'lucide-react';
import type { ApprovalRequest } from '../types';

export const ApprovalsPanel: React.FC = () => {
  const [approvals, setApprovals] = useState<ApprovalRequest[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [processingId, setProcessingId] = useState<string | null>(null);

  const fetchApprovals = async () => {
    setIsLoading(true);
    try {
      const res = await fetch('/approvals/api/pending');
      if (res.ok) {
        const data = await res.json();
        setApprovals(data || []);
      }
    } catch (e) {
      console.error('Fetch approvals error', e);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchApprovals();
    const interval = setInterval(fetchApprovals, 5000);
    return () => clearInterval(interval);
  }, []);

  const handleApprove = async (approvalId: string) => {
    setProcessingId(approvalId);
    try {
      const res = await fetch(`/approvals/api/${approvalId}/approve`, {
        method: 'POST',
      });
      if (res.ok) {
        await fetchApprovals();
      }
    } catch (e) {
      console.error('Approve error', e);
    } finally {
      setProcessingId(null);
    }
  };

  const handleReject = async (approvalId: string) => {
    setProcessingId(approvalId);
    try {
      const res = await fetch(`/approvals/api/${approvalId}/reject`, {
        method: 'POST',
      });
      if (res.ok) {
        await fetchApprovals();
      }
    } catch (e) {
      console.error('Reject error', e);
    } finally {
      setProcessingId(null);
    }
  };

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      <div className="bg-white border border-slate-200/80 rounded-2xl p-7 shadow-soft-md">
        <div className="flex items-center justify-between mb-5">
          <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-slate-500">
            <ShieldCheck className="w-4 h-4 text-brand-600" />
            <span>Human-in-the-Loop Compliance Gate</span>
          </div>
          <button
            onClick={fetchApprovals}
            disabled={isLoading}
            className="flex items-center gap-2 px-4 py-2 bg-slate-100 hover:bg-slate-200 text-slate-700 font-semibold rounded-xl text-xs transition-all shadow-soft-sm"
          >
            <RefreshCw className={`w-3.5 h-3.5 ${isLoading ? 'animate-spin' : ''}`} />
            <span>Refresh Queue</span>
          </button>
        </div>

        <p className="text-sm text-slate-600 leading-relaxed mb-6">
          Action requests generated by downstream agents carrying binding or external effects require explicit human compliance officer authorization before execution by the Tool-Exec Agent.
        </p>

        {approvals.length === 0 ? (
          <div className="p-10 text-center border-2 border-dashed border-slate-200 rounded-2xl bg-slate-50/50">
            <Clock className="w-10 h-10 text-slate-400 mx-auto mb-3" />
            <div className="text-sm font-bold text-slate-800 mb-1">Approval Queue Active & Empty</div>
            <div className="text-xs text-slate-500 max-w-sm mx-auto leading-relaxed">
              When a query results in a proposed action (e.g. legal_web_search, document_export), it will be queued here for manual verification.
            </div>
          </div>
        ) : (
          <div className="space-y-4">
            {approvals.map((req) => (
              <div
                key={req.approval_id}
                className="p-6 bg-slate-50/90 border border-slate-200 rounded-2xl shadow-soft-sm space-y-4"
              >
                <div className="flex items-center justify-between border-b border-slate-200/80 pb-3">
                  <div className="flex items-center gap-2.5">
                    <div className="w-8 h-8 rounded-xl bg-amber-100 text-amber-800 flex items-center justify-center font-bold text-xs">
                      <AlertTriangle className="w-4 h-4 text-amber-600" />
                    </div>
                    <div>
                      <div className="text-sm font-extrabold text-slate-900 flex items-center gap-2">
                        <span>{req.tool_name}</span>
                        <span className="px-2 py-0.5 bg-amber-100 text-amber-800 text-[10px] font-bold uppercase rounded-md">
                          Pending Approval
                        </span>
                      </div>
                      <div className="text-xs text-slate-500 font-mono">
                        Trace ID: {req.trace_id}
                      </div>
                    </div>
                  </div>
                  <div className="text-xs text-slate-400 font-medium">
                    Requested by {req.requested_by}
                  </div>
                </div>

                <div className="bg-white p-4 rounded-xl border border-slate-200/70 space-y-2">
                  <div className="text-xs font-extrabold text-slate-500 uppercase tracking-wider flex items-center gap-1.5">
                    <Terminal className="w-3.5 h-3.5 text-slate-400" />
                    Target Parameters / Search Query
                  </div>
                  <pre className="text-xs font-mono text-slate-800 bg-slate-50 p-2.5 rounded-lg overflow-x-auto">
                    {JSON.stringify(req.parameters_parsed || req.parameters, null, 2)}
                  </pre>
                </div>

                <div className="flex items-center justify-end gap-3 pt-2">
                  <button
                    onClick={() => handleReject(req.approval_id)}
                    disabled={processingId === req.approval_id}
                    className="flex items-center gap-1.5 px-4 py-2 bg-slate-200 hover:bg-rose-100 text-slate-700 hover:text-rose-800 font-bold rounded-xl text-xs transition-all shadow-soft-sm"
                  >
                    <XCircle className="w-4 h-4 text-rose-600" />
                    <span>Reject</span>
                  </button>
                  <button
                    onClick={() => handleApprove(req.approval_id)}
                    disabled={processingId === req.approval_id}
                    className="flex items-center gap-1.5 px-5 py-2 bg-emerald-600 hover:bg-emerald-700 text-white font-bold rounded-xl text-xs transition-all shadow-soft-sm"
                  >
                    <CheckCircle2 className="w-4 h-4 text-white" />
                    <span>{processingId === req.approval_id ? 'Executing...' : 'Approve & Execute'}</span>
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
};
